### PR TITLE
Apple Corp main page #

### PR DESCRIPTION
**Pull request by Bekhzod96**
This project consists of building a webpage using images as a background and adding gradients to elements. In this project, I cloned the website of one of the most design-forward companies in the world. It’s not a very complex site but it uses background photos well and the navbar at the top contains a gradient that you should be able to mimic

### CODE REVIEW

**Comment by uryelah** [comment]
Hello **Beka Akhrorov**, I'm Sarah, your reviewer for this PR 👩‍🚀  

**You did a really great job. One can see how much effort you put into this project 🎇🎆**
You are almost there, there are some issues you'll need to fix though.

---------    

**Great job at: 🥇** 
- having great attention to detail
- applying your gradients well
- using semantic HTML
- styling the text color, opacity and overall style
- using google fonts to match the original site font
- adding the icon at the footer
- adding hover effects

**You still need to fix some minor issues below before you can move to the next project**

---------

### Required changes 🛠 

- [ ] Make sure your HTML passes the validator before submitting a next code review request. There's a warning showing up at the moment [Test your mark up here](https://validator.w3.org/#validate_by_upload).

### Optional enhancements

- [ ] [OPTIONAL] There's some margin between the main image and the ones in the bottom in the [original site](https://web.archive.org/web/20140301004610/http://www.apple.com/).
Add that and your clone will be nearly perfect!
Your version:
Screenshot_2020-03-06 Apple Corp
Original:
Screenshot_2020-03-06 Apple(5)



---------

**Please fix the required change 👷  before asking for a new code review**

---------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Great work @Bekhzod96! :rocket: 
Your project is coming together really nicely, please look into the comments I have left below, make the necessary changes and request another review!

#### Fullscreen
Please note that the project is meant to be fullscreen, stretching from one end of the browser to another. Yours seems to have a little bit of padding on the left and right sides of it. Please consider looking into this, and make the necessary changes before your next review!

#### Use of background images
Please consider that as per the requirements for this project, the images in the footer are supposed to be `<div>` tags with their `background-image` properties set to the image URL and not image tags inside divs
screenshot

#### Stickler errors
You have done very nicely by including stickler in your project as requested! However, you need to ensure that all errors it throws are appropriately addressed before you request a PR review. Please look into this, address appropriately and request another review. 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes ♻️ 🚥 

Hi @Bekhzod96, you have done a great job fixing the commended changes 👍 Kindly fix comment before we can approve your project
- ```Stickler``` is removed, kindly put it back and let us pass stickler checks before we can proceed 🙂
- Let us add ```<a>``` to the ```copyright``` text in the ```<footer>```

Kindly make these changes and submit another code review 👍 
_Happy coding_ 👨‍💻 
@slack on **Daniel Larbi Addo**

**Review by nikasulo — APPROVED** [review]
# Great work @Bekhzod96 and @uryelah ! :rocket:
Please merge and keep moving forward! Your project looks really great, and wish you the very best moving forward :handshake: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Pull request merged**
